# acceptance tests require access to internal resources
---
.travis.yml:
  docker_sets: []
  includes:
  - rvm: 2.3.1
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.1.7
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 4.0"
  extras:
    - rvm: 2.1.9
      script: bundle exec rake rubocop
appveyor.yml:
  delete: true
spec/spec_helper.rb:
  allow_deprecations: true
